export const WEATHER_CODES = {
  clear: [0, 1],
  cloudy: [2, 3],
  fog: [45, 48],
  drizzle: [51, 53, 55],
  rain: [61, 63, 65, 80, 81, 82],
  snow: [71, 73, 75],
  thunderstorm: [95, 96, 99],
  // 0: "Clear sky",
  // 1: "Mainly clear",
  // 2: "Partly cloudy",
  // 3: "Overcast",
  // 45: "Fog",
  // 48: "Depositing rime fog",
  // 51: "Drizzle: Light",
  // 53: "Drizzle: Moderate",
  // 55: "Drizzle: Dense",
  // 61: "Rain: Slight",
  // 63: "Rain: Moderate",
  // 65: "Rain: Heavy",
  // 71: "Snow: Slight",
  // 73: "Snow: Moderate",
  // 75: "Snow: Heavy",
  // 80: "Rain showers: Slight",
  // 81: "Rain showers: Moderate",
  // 82: "Rain showers: Violent",
  // 95: "Thunderstorm",
  // 96: "Thunderstorm + hail (slight)",
  // 99: "Thunderstorm + hail (heavy)",
};
